"""init

Revision ID: 16ff8aae2e3f
Revises: 2d8732752955
Create Date: 2023-04-04 21:22:54.946704

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '16ff8aae2e3f'
down_revision = '2d8732752955'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
