"""add year

Revision ID: 1e8fea19c2a9
Revises: c2b7dd74914e
Create Date: 2023-04-03 20:02:36.178928

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '1e8fea19c2a9'
down_revision = 'c2b7dd74914e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
