"""add year

Revision ID: 7f2d81196978
Revises: 1287ad5def4f
Create Date: 2023-04-04 21:14:18.460780

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '7f2d81196978'
down_revision = '1287ad5def4f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
