"""init

Revision ID: a5ec06af87b7
Revises: 1e8fea19c2a9
Create Date: 2023-04-03 20:19:59.163815

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'a5ec06af87b7'
down_revision = '1e8fea19c2a9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
