"""init

Revision ID: e47d168f9e1e
Revises: a5ec06af87b7
Create Date: 2023-04-03 20:22:38.722819

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'e47d168f9e1e'
down_revision = 'a5ec06af87b7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
