version: '3'

volumes:
  base-data:
  gpt-database-data:
  gpt-nginx-data:
  redis-data:

services:
  gpt-database:
    image: postgres:15-alpine
    env_file:
      - .env
    restart: always
    ports:
      - '5431:5432'
    volumes:
      - gpt-database-data:/var/lib/postgresql/data
    logging:
      driver: "none"

  gpt-backend:
    restart: always
    env_file:
      - .env
    build:
      context: ./gpt-backend
      dockerfile: ./Dockerfile
      args:
        env: ${ENV}
    ports:
      - "8666:8000"
    command: |
        bash -c "
        while !</dev/tcp/gpt-database/5432; do sleep 1; done;
        gunicorn src.main:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 --log-level=debug --timeout=60 --reload"
    depends_on:
      - gpt-database
    environment:
      - PYTHONUNBUFFERED=0
    volumes:
      - base-data:/data
      - ./gpt-backend/:/code

  gpt-frontend:
    build:
      context: ./gpt-frontend
      dockerfile: ./Dockerfile
      args:
        env: ${ENV}
    ports:
      - "3000:3000"
    depends_on:
      - gpt-backend
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    restart: always

#  gpt-nginx:
#    restart: always
#    ports:
#      - "0.0.0.0:80:80"
#    env_file:
#      - .env
#    build:
#      context: ./gpt-nginx
#      dockerfile: ./Dockerfile
#    volumes:
#        - gpt-nginx-data:/etc/letsencrypt
#
#  redis:
#    restart: always
#    image: redis:latest
#    ports:
#      - "6479:6379"
#    volumes:
#      - redis-data:/data
